spine:
      hosts:
         spine01:
            ansible_host: 192.168.56.101
         spine02:
            ansible_host: 192.168.56.102
leaf:
      hosts:
         leaf01:
            ansible_host: 192.168.56.103
         leaf02:
            ansible_host: 192.168.56.104
         leaf03:
            ansible_host: 192.168.56.105
         leaf04:
            ansible_host: 192.168.56.106
