spine:
      vars:
            ansible_connection: network_cli
            ansible_network_os: eos
            ansible_user: admin
            ansible_password: admin
      hosts:
         spine01:
            ansible_host: localhost
            ansible_port: 11001
         spine02:
            ansible_host: localhost
            ansible_port: 11002
leaf:
      vars:
            ansible_connection: network_cli
            ansible_host: localhost
            ansible_network_os: eos
            ansible_user: admin
            ansible_password: admin
      hosts:
         leaf01:
            ansible_port: 11003
         leaf02:
            ansible_port: 11004
         leaf03:
            ansible_port: 11005
         leaf04:
            ansible_port: 11006
